#:import vector kivy.vector.Vector

<Game>:
	street: street
	street2: street2
	
	Image:
		id: street
		source:'images/street1.png'
		size_hint:None,None
		allow_stretch: True
		scale: root.height/self.texture_size[1]
		size: vector(self.texture_size)*self.scale
	
	Image:
		id: street2
		source:'images/street1.png'
		size_hint:None,None
		allow_stretch: True
		scale: root.height/self.texture_size[1]
		size: vector(self.texture_size)*self.scale
		x:street.right
		
